- hosts: fortigate01
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 8080
  tasks:
    - name: Configure global attributes.
      fortinet.fortios.fortios_system_global:
        vdom:  "{{ vdom }}"
        system_global:
            hostname: 'AZUVNLABFGT001'


    - name: fortios_firewall_vip
      fortinet.fortios.fortios_firewall_vip:
        vdom: "{{ vdom }}"
        state: present
        firewall_vip:
          extintf: any
          extip: 10.10.0.4
          extport: '80'
          mappedip: 
            - range: 10.10.0.132-10.10.0.132
          mappedport: '80'
          name: WEB-SRV
          portforward: enable
          portmapping_type: 1-to-1
          protocol: tcp

    - name: fortios_firewall_policy
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          name: Allow_Inbound_Web
          srcintf:
            - name: port1
          dstintf:
            - name: port2
          srcaddr:
            - name: all
          dstaddr:
            - name: WEB-SRV
          action: accept
          policyid: 2
          nat: enable
          logtraffic: all
          schedule: always
          service:
            - name: ALL
          ssl_ssh_profile: certificate-inspection

    - name: fortios_firewall_policy2
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          name: Allow_Outbound
          srcintf:
            - name: port2
          dstintf:
            - name: port1
          srcaddr:
            - name: all
          dstaddr:
            - name: all
          action: accept
          policyid: 3
          nat: enable
          logtraffic: all
          schedule: always
          service:
            - name: ALL
          ssl_ssh_profile: certificate-inspection


    - name: fortios_router_static-1
      fortinet.fortios.fortios_router_static:
        vdom: "{{ vdom }}"
        state: present
        router_static:
          device: port2
          distance: 10
          dst: 10.10.0.128/26
          dynamic_gateway: disable
          gateway: 10.10.0.65
          priority: 0
          seq_num: 2
          src: 0.0.0.0 0.0.0.0
          status: enable

    - name: fortios_router_static
      fortinet.fortios.fortios_router_static:
        vdom: "{{ vdom }}"
        state: present
        router_static:
          device: port1
          distance: 1
          dst: 0.0.0.0 0.0.0.0
          dynamic_gateway: disable
          gateway: 10.10.0.1
          priority: 0
          seq_num: 3
          src: 10.10.0.0/24
          status: enable

- hosts: fortigate02
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 8080
   
  tasks:
    - name: Configure global attributes.
      fortinet.fortios.fortios_system_global:
        vdom:  "{{ vdom }}"
        system_global:
            hostname: 'AZUVNLABFGT002'

    - name: fortios_firewall_vip
      fortinet.fortios.fortios_firewall_vip:
        vdom: "{{ vdom }}"
        state: present
        firewall_vip:
          extintf: any
          extip: 10.10.0.5
          extport: '80'
          mappedip: 
            - range: 10.10.0.132-10.10.0.132
          mappedport: '80'
          name: WEB-SRV
          portforward: enable
          portmapping_type: 1-to-1
          protocol: tcp

    - name: fortios_firewall_policy
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          name: Allow_Inbound_Web
          srcintf:
            - name: port1
          dstintf:
            - name: port2
          srcaddr:
            - name: all
          dstaddr:
            - name: WEB-SRV
          action: accept
          policyid: 2
          nat: enable
          logtraffic: all
          schedule: always
          service:
            - name: ALL
          ssl_ssh_profile: certificate-inspection

    - name: fortios_firewall_policy2
      fortinet.fortios.fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          name: Allow_Outbound
          srcintf:
            - name: port2
          dstintf:
            - name: port1
          srcaddr:
            - name: all
          dstaddr:
            - name: all
          action: accept
          policyid: 3
          nat: enable
          logtraffic: all
          schedule: always
          service:
            - name: ALL
          ssl_ssh_profile: certificate-inspection


    - name: fortios_router_static-1
      fortinet.fortios.fortios_router_static:
        vdom: "{{ vdom }}"
        state: present
        router_static:
          device: port2
          distance: 10
          dst: 10.10.0.128/26
          dynamic_gateway: disable
          gateway: 10.10.0.65
          priority: 0
          seq_num: 2
          src: 0.0.0.0 0.0.0.0
          status: enable

    - name: fortios_router_static
      fortinet.fortios.fortios_router_static:
        vdom: "{{ vdom }}"
        state: present
        router_static:
          device: port1
          distance: 1
          dst: 0.0.0.0 0.0.0.0
          dynamic_gateway: disable
          gateway: 10.10.0.1
          priority: 0
          seq_num: 3
          src: 10.10.0.0/24
          status: enable

